"""Seed catalog: system roles, the permission catalog, and role→permission maps.

This is the single source of truth for what each role may do. The idempotent
seeder (app/seed/run.py) applies it. super_admin receives every permission
automatically.
"""

# ── System roles ──────────────────────────────────────────────────────────────
ROLES: list[dict] = [
    {"name": "super_admin", "description": "Full system access", "is_system_role": True},
    {"name": "hostel_admin", "description": "Overall hostel administration", "is_system_role": True},
    {"name": "warden", "description": "Resident operations", "is_system_role": True},
    {"name": "accountant", "description": "Finance operations", "is_system_role": True},
    {"name": "receptionist", "description": "Front-desk operations", "is_system_role": True},
    {"name": "security_guard", "description": "Security operations", "is_system_role": True},
    {"name": "mess_manager", "description": "Mess operations", "is_system_role": True},
    {"name": "maintenance_staff", "description": "Maintenance operations", "is_system_role": True},
    {"name": "inventory_manager", "description": "Inventory and assets", "is_system_role": True},
    {"name": "resident", "description": "Resident self-service", "is_system_role": True},
]

# ── Permission catalog ────────────────────────────────────────────────────────
# name: module.action  — module groups permissions in the API/UI.
PERMISSIONS: list[dict] = [
    # Users / staff / roles / permissions
    {"name": "users.view", "module": "users", "description": "View user accounts"},
    {"name": "users.create", "module": "users", "description": "Create user accounts"},
    {"name": "users.update", "module": "users", "description": "Update user accounts"},
    {"name": "staff.view", "module": "staff", "description": "View staff records"},
    {"name": "staff.create", "module": "staff", "description": "Create staff records"},
    {"name": "staff.update", "module": "staff", "description": "Update staff records"},
    {"name": "roles.view", "module": "roles", "description": "View roles"},
    {"name": "roles.manage", "module": "roles", "description": "Manage roles and role permissions"},
    {"name": "permissions.view", "module": "permissions", "description": "View permission catalog"},
    # Hostel structure
    {"name": "hostel_settings.view", "module": "hostel_settings", "description": "View hostel settings"},
    {"name": "hostel_settings.manage", "module": "hostel_settings", "description": "Manage hostel settings"},
    {"name": "buildings.view", "module": "buildings", "description": "View buildings"},
    {"name": "buildings.create", "module": "buildings", "description": "Create buildings"},
    {"name": "buildings.update", "module": "buildings", "description": "Update buildings"},
    {"name": "floors.view", "module": "floors", "description": "View floors"},
    {"name": "floors.create", "module": "floors", "description": "Create floors"},
    {"name": "floors.update", "module": "floors", "description": "Update floors"},
    {"name": "rooms.view", "module": "rooms", "description": "View rooms"},
    {"name": "rooms.create", "module": "rooms", "description": "Create rooms"},
    {"name": "rooms.update", "module": "rooms", "description": "Update rooms"},
    {"name": "beds.view", "module": "beds", "description": "View beds"},
    {"name": "beds.create", "module": "beds", "description": "Create beds"},
    {"name": "beds.update", "module": "beds", "description": "Update beds"},
    # Residents
    {"name": "residents.view", "module": "residents", "description": "View all residents"},
    {"name": "residents.view_limited", "module": "residents", "description": "View limited resident info (security)"},
    {"name": "residents.view_own", "module": "residents", "description": "View own resident profile"},
    {"name": "residents.create", "module": "residents", "description": "Create residents"},
    {"name": "residents.update", "module": "residents", "description": "Update any resident"},
    {"name": "residents.update_own", "module": "residents", "description": "Update own resident profile"},
    {"name": "residents.checkout", "module": "residents", "description": "Check out a resident and release their bed"},
    {"name": "residents.mark_returned", "module": "residents", "description": "Mark a resident as returned from leave"},
    {"name": "resident_documents.view", "module": "resident_documents", "description": "View resident documents"},
    {"name": "resident_documents.view_own", "module": "resident_documents", "description": "View own documents"},
    {"name": "resident_documents.manage", "module": "resident_documents", "description": "Manage resident documents"},
    {"name": "resident_documents.manage_own", "module": "resident_documents", "description": "Manage own documents"},
    {"name": "emergency_contacts.view", "module": "emergency_contacts", "description": "View emergency contacts"},
    {"name": "emergency_contacts.view_own", "module": "emergency_contacts", "description": "View own emergency contacts"},
    {"name": "emergency_contacts.manage", "module": "emergency_contacts", "description": "Manage emergency contacts"},
    {"name": "emergency_contacts.manage_own", "module": "emergency_contacts", "description": "Manage own emergency contacts"},
    # Admissions / allocation / stays
    {"name": "admissions.view", "module": "admissions", "description": "View all admissions"},
    {"name": "admissions.view_own", "module": "admissions", "description": "View own admission"},
    {"name": "admissions.create", "module": "admissions", "description": "Create admissions"},
    {"name": "admissions.update", "module": "admissions", "description": "Update admissions"},
    {"name": "admissions.approve", "module": "admissions", "description": "Approve admissions"},
    {"name": "admissions.reject", "module": "admissions", "description": "Reject admissions"},
    {"name": "allocations.view", "module": "allocations", "description": "View room allocations"},
    {"name": "allocations.view_own", "module": "allocations", "description": "View own allocation"},
    {"name": "allocations.create", "module": "allocations", "description": "Create allocations"},
    {"name": "allocations.update", "module": "allocations", "description": "Update allocations"},
    {"name": "allocations.transfer", "module": "allocations", "description": "Transfer allocations"},
    {"name": "stays.view", "module": "stays", "description": "View resident stays"},
    {"name": "stays.view_own", "module": "stays", "description": "View own stay"},
    {"name": "stays.create", "module": "stays", "description": "Create stays"},
    {"name": "stays.update", "module": "stays", "description": "Update stays"},
    {"name": "stays.check_in", "module": "stays", "description": "Perform check-in"},
    {"name": "stays.check_out", "module": "stays", "description": "Perform check-out"},
    # Daily operations
    {"name": "attendance.view", "module": "attendance", "description": "View attendance"},
    {"name": "attendance.view_own", "module": "attendance", "description": "View own attendance"},
    {"name": "attendance.mark", "module": "attendance", "description": "Mark attendance"},
    {"name": "attendance.update", "module": "attendance", "description": "Update attendance"},
    {"name": "leave_requests.view", "module": "leave_requests", "description": "View leave requests"},
    {"name": "leave_requests.view_own", "module": "leave_requests", "description": "View own leave requests"},
    {"name": "leave_requests.create", "module": "leave_requests", "description": "Create leave requests"},
    {"name": "leave_requests.approve", "module": "leave_requests", "description": "Approve leave requests"},
    {"name": "leave_requests.reject", "module": "leave_requests", "description": "Reject leave requests"},
    {"name": "visitors.view", "module": "visitors", "description": "View visitors"},
    {"name": "visitors.view_own", "module": "visitors", "description": "View own visitors"},
    {"name": "visitors.create", "module": "visitors", "description": "Register visitors"},
    {"name": "visitors.create_own", "module": "visitors", "description": "Register a guest for yourself"},
    {"name": "visitor_logs.view", "module": "visitor_logs", "description": "View visitor logs"},
    {"name": "visitor_logs.create", "module": "visitor_logs", "description": "Check visitors in/out"},
    {"name": "gate_passes.view", "module": "gate_passes", "description": "View gate passes"},
    {"name": "gate_passes.view_own", "module": "gate_passes", "description": "View own gate passes"},
    {"name": "gate_passes.create", "module": "gate_passes", "description": "Create gate passes"},
    {"name": "gate_passes.approve", "module": "gate_passes", "description": "Approve gate passes"},
    {"name": "gate_passes.reject", "module": "gate_passes", "description": "Reject gate passes"},
    {"name": "gate_passes.issue", "module": "gate_passes", "description": "Issue gate passes"},
    {"name": "gate_passes.verify", "module": "gate_passes", "description": "Verify gate pass exit/return"},
    # Finance
    {"name": "fee_structures.view", "module": "fee_structures", "description": "View fee structures"},
    {"name": "fee_structures.manage", "module": "fee_structures", "description": "Manage fee structures"},
    {"name": "resident_charges.view", "module": "resident_charges", "description": "View resident charges"},
    {"name": "resident_charges.create", "module": "resident_charges", "description": "Create resident charges"},
    {"name": "resident_charges.update", "module": "resident_charges", "description": "Update resident charges"},
    {"name": "invoices.view", "module": "invoices", "description": "View all invoices"},
    {"name": "invoices.view_own", "module": "invoices", "description": "View own invoices"},
    {"name": "invoices.create", "module": "invoices", "description": "Create invoices"},
    {"name": "invoices.update", "module": "invoices", "description": "Update invoices"},
    {"name": "payments.view", "module": "payments", "description": "View all payments"},
    {"name": "payments.view_own", "module": "payments", "description": "View own payments"},
    {"name": "payments.create", "module": "payments", "description": "Record payments"},
    {"name": "expenses.view", "module": "expenses", "description": "View expenses"},
    {"name": "expenses.create", "module": "expenses", "description": "Record expenses"},
    {"name": "expenses.update", "module": "expenses", "description": "Update expenses"},
    {"name": "security_deposits.view", "module": "security_deposits", "description": "View security deposits"},
    {"name": "security_deposits.manage", "module": "security_deposits", "description": "Manage security deposits"},
    # Maintenance & inventory
    {"name": "complaints.view", "module": "complaints", "description": "View complaints"},
    {"name": "complaints.view_own", "module": "complaints", "description": "View own complaints"},
    {"name": "complaints.create", "module": "complaints", "description": "Create complaints"},
    {"name": "complaints.update", "module": "complaints", "description": "Update complaints"},
    {"name": "maintenance_tickets.view", "module": "maintenance_tickets", "description": "View maintenance tickets"},
    {"name": "maintenance_tickets.create", "module": "maintenance_tickets", "description": "Create maintenance tickets"},
    {"name": "maintenance_tickets.update", "module": "maintenance_tickets", "description": "Update maintenance tickets"},
    {"name": "inventory_categories.view", "module": "inventory_categories", "description": "View inventory categories"},
    {"name": "inventory_categories.manage", "module": "inventory_categories", "description": "Manage inventory categories"},
    {"name": "inventory_items.view", "module": "inventory_items", "description": "View inventory items"},
    {"name": "inventory_items.update", "module": "inventory_items", "description": "Update inventory item details and quantities"},
    {"name": "inventory_items.manage", "module": "inventory_items", "description": "Manage inventory items"},
    {"name": "assets.view", "module": "assets", "description": "View assets"},
    {"name": "assets.manage", "module": "assets", "description": "Manage assets"},
    {"name": "asset_assignments.view", "module": "asset_assignments", "description": "View asset assignments"},
    {"name": "asset_assignments.manage", "module": "asset_assignments", "description": "Manage asset assignments"},
    # Mess & communication
    {"name": "mess_menus.view", "module": "mess_menus", "description": "View mess menus"},
    {"name": "mess_menus.create", "module": "mess_menus", "description": "Create mess menus"},
    {"name": "mess_menus.update", "module": "mess_menus", "description": "Update mess menus"},
    {"name": "mess_menus.delete", "module": "mess_menus", "description": "Delete mess menus"},
    {"name": "meals.view", "module": "meals", "description": "View meal records"},
    {"name": "meals.create", "module": "meals", "description": "Mark meals"},
    {"name": "meals.update", "module": "meals", "description": "Update meal records"},
    {"name": "notices.view", "module": "notices", "description": "View notices"},
    {"name": "notices.create", "module": "notices", "description": "Create notices"},
    {"name": "notices.update", "module": "notices", "description": "Update notices"},
    {"name": "notices.publish", "module": "notices", "description": "Publish/unpublish notices"},
    {"name": "notifications.view", "module": "notifications", "description": "View own notifications"},
    {"name": "notifications.manage", "module": "notifications", "description": "Manage notifications (read state)"},
    # System
    {"name": "audit_logs.view", "module": "audit_logs", "description": "View audit logs"},
    {"name": "reports.view", "module": "reports", "description": "View reports"},
]

# ── Role → permissions ────────────────────────────────────────────────────────
# super_admin is not listed here; it receives every permission automatically.
ROLE_PERMISSIONS: dict[str, list[str]] = {
    "hostel_admin": [
        "users.view",
        "staff.view",
        "buildings.view", "buildings.create", "buildings.update",
        "floors.view", "floors.create", "floors.update",
        "rooms.view", "rooms.create", "rooms.update",
        "beds.view", "beds.create", "beds.update",
        "hostel_settings.view", "hostel_settings.manage",
        "residents.view", "residents.create", "residents.update", "residents.checkout", "residents.mark_returned",
        "resident_documents.view", "resident_documents.manage",
        "emergency_contacts.view", "emergency_contacts.manage",
        "admissions.view", "admissions.create", "admissions.update",
        "admissions.approve", "admissions.reject",
        "allocations.view", "allocations.create", "allocations.update", "allocations.transfer",
        "stays.view", "stays.create", "stays.check_in", "stays.check_out",
        "attendance.view", "attendance.mark", "attendance.update",
        "leave_requests.view", "leave_requests.approve", "leave_requests.reject",
        "visitors.view", "visitors.create",
        "visitor_logs.view", "visitor_logs.create",
        "gate_passes.view", "gate_passes.approve", "gate_passes.reject", "gate_passes.issue",
        "complaints.view", "complaints.update",
        "maintenance_tickets.view", "maintenance_tickets.create",
        "mess_menus.view",
        "meals.view",
        "notices.view", "notices.create",
        "notifications.manage",
        "invoices.view", "payments.view", "expenses.view",
        "reports.view",
    ],
    "warden": [
        "residents.view", "residents.create", "residents.update", "residents.checkout", "residents.mark_returned",
        "admissions.view", "admissions.create", "admissions.update", "admissions.approve",
        "rooms.view", "beds.view",
        "allocations.view", "allocations.create", "allocations.update",
        "stays.view", "stays.create", "stays.update", "stays.check_in", "stays.check_out",
        "attendance.view", "attendance.mark", "attendance.update",
        "leave_requests.view", "leave_requests.approve", "leave_requests.reject",
        "visitors.view", "visitor_logs.view",
        "gate_passes.view", "gate_passes.approve", "gate_passes.reject",
        "complaints.view", "complaints.update",
        "maintenance_tickets.view",
    ],
    "accountant": [
        "fee_structures.view", "fee_structures.manage",
        "resident_charges.view", "resident_charges.create", "resident_charges.update",
        "invoices.view", "invoices.create", "invoices.update",
        "payments.view", "payments.create",
        "expenses.view", "expenses.create", "expenses.update",
        "security_deposits.view", "security_deposits.manage",
        "reports.view",
    ],
    "receptionist": [
        "residents.view", "residents.create", "residents.update",
        "admissions.view", "admissions.create", "admissions.update",
        "rooms.view", "beds.view",
        "allocations.view", "allocations.create",
        "visitors.view", "visitors.create",
        "visitor_logs.view",
        "gate_passes.view",
    ],
    "security_guard": [
        "residents.view_limited",
        "visitors.view", "visitors.create",
        "visitor_logs.view", "visitor_logs.create",
        "gate_passes.view", "gate_passes.issue", "gate_passes.verify",
    ],
    "mess_manager": [
        "mess_menus.view", "mess_menus.create", "mess_menus.update", "mess_menus.delete",
        "meals.view", "meals.create", "meals.update",
    ],
    "maintenance_staff": [
        "complaints.view", "complaints.update",
        "maintenance_tickets.view", "maintenance_tickets.create", "maintenance_tickets.update",
        "inventory_items.view", "inventory_items.update",
    ],
    "inventory_manager": [
        "inventory_categories.view", "inventory_categories.manage",
        "inventory_items.view", "inventory_items.manage",
        "assets.view", "assets.manage",
        "asset_assignments.view", "asset_assignments.manage",
    ],
    "resident": [
        "residents.view_own", "residents.update_own",
        "resident_documents.view_own", "resident_documents.manage_own",
        "emergency_contacts.view_own", "emergency_contacts.manage_own",
        "admissions.view_own",
        "allocations.view_own", "stays.view_own",
        "attendance.view_own",
        "leave_requests.create", "leave_requests.view_own",
        "visitors.view_own", "visitors.create_own",
        "gate_passes.create", "gate_passes.view_own",
        "invoices.view_own", "payments.view_own",
        "complaints.create", "complaints.view_own",
        "notices.view",
        "notifications.view",
    ],
}
